chore: updating husky pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,7 @@
+# Step 1: Run lint-staged
+echo "Running lint & format on staged files..."
 pnpm run lint-staged
+if [ $? -ne 0 ]; then
+  echo "lint-staged failed. Aborting push."
+  exit 1
+fi
